name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Build Frontend Docker Image
      run: |
        cd apps/frontend
        docker build -t okejoshua/frontend:${{ github.sha }} .
        docker build -t okejoshua/frontend:latest .
    
    - name: Push Docker Images
      run: |
        echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
        docker push okejoshua/frontend:${{ github.sha }}
        docker push okejoshua/frontend:latest

  build-backend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    
    - name: Build with Maven
      run: |
        cd apps/backend
        mvn clean package
    
    - name: Build Backend Docker Image
      run: |
        cd apps/backend
        docker build -t okejoshua/backend:${{ github.sha }} .
        docker build -t okejoshua/backend:latest .
    
    - name: Push Docker Images
      run: |
        echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
        docker push okejoshua/backend:${{ github.sha }}
        docker push okejoshua/backend:latest
